package org.pgs.study.json.entry;

import org.pgs.pglink.Console;
import org.pgs.study.json.impl.EngineTypeAdapter;
import org.pgs.study.json.obj.Car;
import org.pgs.study.json.obj.Engine;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;

/**
 * The {@code GsonVersion} is the demonstration of the JSON study document
 * chapter 3.7.2 - Type Adapter.
 *
 * @author PGKan
 */
public class GsonTypeAdapter {

	public static void main(String[] args) {
		Gson gson = new GsonBuilder()
			.registerTypeAdapter(Engine.class, new EngineTypeAdapter())
			.setPrettyPrinting()
			.create();
		// serialize MODEL_CAR with the write method of the implemented adapter
		String car = gson.toJson(Car.MODEL_CAR);
		Console.println("The JSON string generated by the type adapter:");
		Console.println(car);
		// deserialize MODEL_CAR with the read method of the implemented adapter
		Console.println("\nThe Engine parsed by the type adapter:");
		Console.println(gson.fromJson(car, Car.class));
	}

}
